//https://leetcode.com/problems/find-the-difference/description/
//
//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output :
//	e
//
//	Explanation :
//'e' is the letter that was added.



#include <iostream>
#include <math.h>
#include <algorithm>
#include<vector>
#include<string>
#include <queue>
#include <stack>
#include <list>
#include <map>   //hash table
#include<unordered_map>
#include <vector>
using namespace std;

class Solution {
public:
	char findTheDifference(string s, string t) {
		int key = 0, i = 0;
		while (s[i]) {
			key += t[i] - s[i];
			i++;
		}
		return key + t[i];

	}
};

//3.95% 8m
class Solution2 {
public:
	char findTheDifference(string s, string t) {
		map<char, int>myMap;
		for (int i = 0; i < t.size(); i++) {
			myMap[t[i]]++;
		}
		for (int i = 0; i < s.size(); i++) {
			myMap[s[i]]--;
		}
		for (int i = 0; i < t.size(); i++) {// auto p:myMap will loop every index. 
			if (myMap[t[i]] == 1) {
				return t[i];
			}
		}
	}
};

int main()
{

	vector<int>nums({ 3, 1 ,0 });
	Solution question;
	question.findTheDifference("abcd","edabc");
	Solution question2;
	question2.findTheDifference("dfd", "dfj");

	return 0;
}
